In [1]:
states = ('H', 'G', 'F', 'D')

In [2]:
import numpy as np

In [3]:
tran_prob = np.array([0.5, 0.4, 0.0, 0.1, 0.2, 0.1, 0.6, 0.1, 0.9, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 1.0]).reshape(4,4)



In [4]:
tran_prob

array([[0.5, 0.4, 0. , 0.1],
       [0.2, 0.1, 0.6, 0.1],
       [0.9, 0. , 0. , 0.1],
       [0. , 0. , 0. , 1. ]])

In [5]:
reward = np.array([0, 1, 10, -10]).reshape(4,1)

In [6]:
reward

array([[  0],
       [  1],
       [ 10],
       [-10]])

In [7]:
gamma = 0.9

In [8]:
v=np.arange(400).reshape(100,4)

In [9]:
v0 = reward
v1 = reward + gamma*np.matmul(tran_prob,v0)
v2 = reward + gamma*np.matmul(tran_prob,v1)
v3 = reward + gamma*np.matmul(tran_prob,v2)

In [10]:
v1

array([[ -0.54],
       [  5.59],
       [  9.1 ],
       [-19.  ]])

In [76]:
def value_interation(initial, gamma, tran_prob, iter_no):
    v0 = initial;
    if iter_no==1:
        return v0
    else:
        return initial + gamma*np.matmul(tran_prob, value_interation(initial, gamma, tran_prob, iter_no - 1))

    

In [78]:
value_interation(reward, gamma, tran_prob, 100)

array([[-39.08502487],
       [-34.71463426],
       [-30.65836548],
       [-99.99734386]])